apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: "pvs-teko7" # Replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: simi97/chat-app
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
          env:
            - name: REDIS_HOST
              value: redis-service
          ports:
            - containerPort: 3000
